const allData = [
    {
        products1: [
            {
                id: "01",
                productName: "SELLORIA Brand A- Adjustable Cap Black Plain Cap UnisexCap Quick Drying Sun Hat forSummers Activites Sports Baseball Hat for Men Pack of 1",
                productImg: "/Total_Image/all image/cap.jpg",
                // productPrice:"",
                productColor: "",
                rating: {
                    rating1: "3.8",
                    ratingImg: "/Total_Image/all image/r.jpg",
                    searchRating: "190",
                    boughtItem: "500+",
                    boughtPreviousItem: "10k+",
                },
                productPrice: {
                    offer: "-72%",
                    productsPrice: "169",
                },
                originalPrice: "₹599",
                morePic: {
                    productImg1: "/Total_Image/all image/newbags/picc1.jpg",
                    productPrice1: "₹499.00",
                    productImg2: "/Total_Image/all image/newbags/picc2.jpg",
                    productPrice2: "₹499.00",
                    productImg3: "/Total_Image/all image/newbags/picc3.jpg",
                    productPrice3: "₹699.00",
                },
                productInfo: {
                    productName1: "HELP PROTECT SUNBURN",
                    productInfo1: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName2: "FOR ALL ACTIVITIES",
                    productInfo2: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName3: "UNIQUE STYLE ",
                    productInfo3: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName4: "SUPERCOOL FABRIC ",
                    productInfo4: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName5: "ONE SIZE FITS MOST ",
                    productInfo5: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                },
                customerRatings: {
                    qualityName1: "Light weight",
                    qualityImg1: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating1: "4.8",
                    qualityName2: "Inhalable",
                    qualityImg2: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating2: "4.8",
                    qualityName3: "Comfort",
                    qualityImg3: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating3: "4.4",
                    qualityName4: "Quality of material",
                    qualityImg4: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating4: "4.2",
                },
                similaritem: {
                    itemImg: "https://m.media-amazon.com/images/I/61OS8zQ9WdL._SS100_.jpg",
                    itemName: "Amazon Brand - Nora Nico Stylish Cotton Adjustable Baseball Cap for Men andWomen,Embroidered Unisex Cap for Summers.",
                    itemPrice: "₹379.00",
                    starImg: "http://127.0.0.1:5500/Total_Image/all%20image/r.jpg",
                },
                columnInfo: {
                    price1: "₹499",
                    price2: ".00",
                    itemImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs5ujkV-nmksjP1qM03e1wLZIZH7X2WmeYS4sgIxcd2maXogRTCaBy&usqp=CAE&s",
                    deliveryDate: "Thursday, 16 May.",
                    quickDeleveryDate: "Tomorrow, 13 May.",
                    quickDeleveryTime: "6 hrs 54 mins.",
                    location: "Amar - Kolkata 700074‌",
                },
                lastDivInfo: {
                    itemImg: "https://m.media-amazon.com/images/G/01/x-locale/checkout/truespc/secured-ssl._CB485936932_.png",
                    newItemPrice: "₹190.00",
                },
                thirdColumn: {
                    itemImg: "https://m.media-amazon.com/images/I/410PFyWS44L._SX569_.jpg",
                    itemName: "RR DESIGN Baseball Caps Unisex 100% Cotton Sports Caps for Men Women Black...",
                    itemPrice1: "₹284",
                    itemPrice2: "05",
                    crossPrice: "₹499.00",

                },
            },
            {
                id: "02",
                productName: "SELLORIA Brand A- Adjustable Cap Black Plain Cap UnisexCap Quick Drying Sun Hat forSummers Activites Sports Baseball Hat for Men Pack of 1",
                productImg: "/Total_Image/all image/cap.jpg",
                // productPrice:"",
                productColor: "",
                rating: {
                    rating1: "3.8",
                    ratingImg: "/Total_Image/all image/r.jpg",
                    searchRating: "190",
                    boughtItem: "500+",
                    boughtPreviousItem: "10k+",
                },
                productPrice: {
                    offer: "-72%",
                    productsPrice: "169",
                },
                originalPrice: "₹599",
                morePic: {
                    productImg1: "/Total_Image/all image/newbags/picc1.jpg",
                    productPrice1: "₹499.00",
                    productImg2: "/Total_Image/all image/newbags/picc2.jpg",
                    productPrice2: "₹499.00",
                    productImg3: "/Total_Image/all image/newbags/picc3.jpg",
                    productPrice3: "₹699.00",
                },
                productInfo: {
                    productName1: "HELP PROTECT SUNBURN",
                    productInfo1: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName2: "FOR ALL ACTIVITIES",
                    productInfo2: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName3: "UNIQUE STYLE ",
                    productInfo3: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName4: "SUPERCOOL FABRIC ",
                    productInfo4: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                    productName5: "ONE SIZE FITS MOST ",
                    productInfo5: "These men caps should be added in your shopping cart, As it has many benefits : It helps you protect your skin from UV rays which indirectly helps you protect from sun burns. Great product to add for your daily use and other daily activities. These men cap might helps you with sweat free and can keep your head dry and comfortable.",
                },
                customerRatings: {
                    qualityName1: "Light weight",
                    qualityImg1: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating1: "4.8",
                    qualityName2: "Inhalable",
                    qualityImg2: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating2: "4.8",
                    qualityName3: "Comfort",
                    qualityImg3: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating3: "4.4",
                    qualityName4: "Quality of material",
                    qualityImg4: "/Total_Image/all image/newbags/ratingImg.jpg",
                    qualityRating4: "4.2",
                },
                similaritem: {
                    itemImg: "https://m.media-amazon.com/images/I/61OS8zQ9WdL._SS100_.jpg",
                    itemName: "Amazon Brand - Nora Nico Stylish Cotton Adjustable Baseball Cap for Men andWomen,Embroidered Unisex Cap for Summers.",
                    itemPrice: "₹379.00",
                    starImg: "http://127.0.0.1:5500/Total_Image/all%20image/r.jpg",
                },
                columnInfo: {
                    price1: "₹499",
                    price2: ".00",
                    itemImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs5ujkV-nmksjP1qM03e1wLZIZH7X2WmeYS4sgIxcd2maXogRTCaBy&usqp=CAE&s",
                    deliveryDate: "Thursday, 16 May.",
                    quickDeleveryDate: "Tomorrow, 13 May.",
                    quickDeleveryTime: "6 hrs 54 mins.",
                    location: "Amar - Kolkata 700074‌",
                },
                lastDivInfo: {
                    itemImg: "https://m.media-amazon.com/images/G/01/x-locale/checkout/truespc/secured-ssl._CB485936932_.png",
                    newItemPrice: "₹190.00",
                },
                thirdColumn: {
                    itemImg: "https://m.media-amazon.com/images/I/410PFyWS44L._SX569_.jpg",
                    itemName: "RR DESIGN Baseball Caps Unisex 100% Cotton Sports Caps for Men Women Black...",
                    itemPrice1: "₹284",
                    itemPrice2: "05",
                    crossPrice: "₹499.00",

                },
            }
        ]
    },
    {
        productsSliderWithPrice: [{
            id: '01',
            box_image: '/Total_image/image2/product2-1.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '02',
            box_image: '/Total_image/image2/product2-2.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '03',
            box_image: '/Total_image/image2/product2-3.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '04',
            box_image: '/Total_image/image2/product2-4.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '05',
            box_image: '/Total_image/image2/product2-5.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '06',
            box_image: '/Total_image/image2/product2-6.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '07',
            box_image: '/Total_image/image2/product2-7.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '08',
            box_image: '/Total_image/image2/product2-8.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '09',
            box_image: '/Total_image/image2/product2-9.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '10',
            box_image: '/Total_image/image2/product2-10.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '11',
            box_image: '/Total_image/image2/product2-11.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        {
            id: '12',
            box_image: '/Total_image/image2/product2-12.jpg',
            item_Offer: '27% off',
            ListPrice: '$19.95',
            prevListPrice: '14.49',
        },
        ]
    },
];
